### ISSUE TITLE
Perfil emprendedor 

### ISSUE THREAD

**Issue by RaquelCC** [mpabarca/SCL007-Hackathon-Fundacion-Banigualdad#3]
Crear **componente** que mostrará la página del perfil del emprendimiento. Debe mostrar: el nombre del emprendimiento, nombre del emprendedor, información del negocio, ubicación, contacto, productos.

**Comment by mpabarca** [comment]
PERFIL PRIVADO:
Crear componente que mostrará la página del perfil del emprendimiento. 
Debe mostrar: el nombre del emprendimiento, nombre del emprendedor, información del negocio, ubicación, contacto, productos, CICLOS, CUOTAS A PAGAR

**Comment by mpabarca** [comment]
PERFIL PUBLICO:
Crear componente que mostrará la página del perfil del emprendimiento. Debe mostrar: el nombre del emprendimiento, nombre del emprendedor, información del negocio, COMUNA, contacto, productos.
